global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: kafka-jmx
    static_configs:
      - targets: ['kafka-jmx-exporter:5556']

  - job_name: kafka-exporter
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['app:8080']
